package com.commend.diplomarbeit.patient;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.context.properties.source.InvalidConfigurationPropertyValueException;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/patient") // This means URL's start with /room (after Application path)
public class PatientController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private PatientRepository patientRepository;

    @GetMapping("") // Zeigt alle Räume an
    public List<Patient> getAllPatients() {
        return patientRepository.findAll();
    }

    @PostMapping("") // Map ONLY POST Requests
    public Patient createPatient(@RequestBody Patient patient) {
        return patientRepository.save(patient);
    }

    // Ändern von Patienteninfos
    @PutMapping("/{id}")
    public ResponseEntity<Patient> updatePatient(@PathVariable("id") int id, @RequestBody Patient patient) throws InvalidConfigurationPropertyValueException {

        Patient p = patientRepository.findById(id).orElseThrow(() -> new InvalidConfigurationPropertyValueException("id", id, "Not found"));

        p.setFn(patient.getFn());
        p.setLn(patient.getLn());
        p.setContent(patient.getContent());
        p.setDrug(patient.getDrug());
        p.setTherapyTime(patient.getTherapyTime());
        p.setMainCaregiver(patient.getMainCaregiver());

        final Patient updatePatient = patientRepository.save(p);
        return ResponseEntity.ok(updatePatient);

    }

    //Gibt den Patienten der jeweiligen ID zurück
    @GetMapping("/{id}")
    public ResponseEntity<Patient> getPatientById(@PathVariable("id") int id) throws InvalidConfigurationPropertyValueException {
        Patient p = patientRepository.findById(id).orElseThrow(() -> new InvalidConfigurationPropertyValueException("id", id, "Not found"));
        return ResponseEntity.ok().body(p);


    }

    // Mit diesem Befehl kann man die Daten eines Patienten über einen ID-Zugriff ganz einfach löschen
    @DeleteMapping("/{id}")
    public String deletePatient(@PathVariable("id") int id) {
        patientRepository.deleteById(id);
        return "Deleted";
    }

    // Mit diesem RequestMapping können die Daten der Räume der jeweiligen Patienten per id abgerufen werden
    @GetMapping("/room/{room_id}")
    public Patient getPatientByRoomId(@PathVariable("room_id") int id) {
        return patientRepository.findByRoomId(id);
    }


    @DeleteMapping("/{room_id}/room")
    public String deletePatientByRoomId(@PathVariable("room_id") int id) {
        patientRepository.deleteByRoomId(id);
        return "Deleted";
    }



}


