package com.commend.diplomarbeit.controllers;

import com.commend.diplomarbeit.models.Patient;
import com.commend.diplomarbeit.models.Room;
import com.commend.diplomarbeit.models.RoomRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private com.commend.diplomarbeit.models.RoomRepository RoomRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewRoom (@RequestParam long number, @RequestParam long patientid, @RequestParam String fn, @RequestParam String ln
            , @RequestParam String content) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Patient p = new Patient();
        p.setPatientid(patientid);
        p.setFn(fn);
        p.setLn(ln);

        Room r = new Room();
        r.setNumber(number);
        r.setPatient(p);
        RoomRepository.save(r);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Room> getAllRooms() {
        // This returns a JSON or XML with the users
        return RoomRepository.findAll();
    }
}
